### ISSUE TITLE
Update footer to be like the design over here: https://www.figma.com/file/VQUJeqPPTpdxtls8VwPoxA/Code-for-Chicago?node-id=160%3A221

### ISSUE THREAD

**Issue by Ryan-Koch** [Code-For-Chicago/code-for-chicago-jekyll#42]
https://www.figma.com/file/VQUJeqPPTpdxtls8VwPoxA/Code-for-Chicago?node-id=160%3A221

**Comment by tnguyen21** [comment]
created a PR for this: https://github.com/Code-For-Chicago/code-for-chicago-jekyll/pull/55

**Comment by Ryan-Koch** [comment]
Merged PR! Thanks for your work here @tnguyen21 /
